# generated by action0-client-openapi v0.1.2 from elevation.yml — do not edit
"""Typed exceptions for the documented error responses."""

from __future__ import annotations

import json
from typing import Any

from action0.client import APIError
from action0.req import Response

from .models import GetV1ElevationError


def decode_error(response: Response) -> Any:
    """
    Decode an error response body as JSON.

    :param response: the non-2xx response
    :return: the decoded payload, or ``None`` when the body is
        empty or not valid JSON
    """
    text = response.body_str()
    if text is None or not text.strip():
        return None
    try:
        return json.loads(text)
    except ValueError:
        return None


class BadRequestError(APIError):
    """Raised for the documented ``400`` answer, parsed into a :py:class:`GetV1ElevationError`."""

    def __init__(self, message: str, *, response: Response, error: GetV1ElevationError) -> None:
        """
        :param message: a human-readable description of the failure
        :param response: the offending response
        :param error: the parsed error payload
        """
        super().__init__(message, request=response.request, response=response)
        self.error = error
        """The parsed error payload."""
