# generated by action0-client-openapi v0.1.2 from elevation.yml — do not edit

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class GetV1ElevationResponse:
    """The ``GetV1ElevationResponse`` model."""

    elevation: list[float] | None = None


def get_v1_elevation_response_from_json(data: Any) -> GetV1ElevationResponse:
    """
    Build a :py:class:`GetV1ElevationResponse` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the GetV1ElevationResponse
    """
    return GetV1ElevationResponse(
        elevation=data.get("elevation"),
    )


@dataclass
class GetV1ElevationError:
    """The ``GetV1ElevationError`` model."""

    error: bool | None = None
    reason: str | None = None


def get_v1_elevation_error_from_json(data: Any) -> GetV1ElevationError:
    """
    Build a :py:class:`GetV1ElevationError` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the GetV1ElevationError
    """
    return GetV1ElevationError(
        error=data.get("error"),
        reason=data.get("reason"),
    )
