# generated by action0-client-openapi v0.1.1 from elevation.yml — do not edit

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class GetV1ElevationResponse:
    """The ``GetV1ElevationResponse`` model."""

    elevation: list[float] | None = None


def get_v1_elevation_response_from_json(data: Any) -> GetV1ElevationResponse:
    """
    Build a :py:class:`GetV1ElevationResponse` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the GetV1ElevationResponse
    """
    return GetV1ElevationResponse(
        elevation=data.get("elevation"),
    )
