# generated by action0-client-openapi v0.1.1 from marine.yml — do not edit
"""Typed API client for Open-Meteo Marine Weather Forecast API 1.0."""

from .client import MarineClient
from .models import GetV1MarineCellSelection
from .models import GetV1MarineCurrentItem
from .models import GetV1MarineDailyItem
from .models import GetV1MarineHourlyItem
from .models import GetV1MarineLengthUnit
from .models import GetV1MarineMinutely15Item
from .models import GetV1MarineModelsItem
from .models import GetV1MarineResponse
from .models import GetV1MarineResponseCurrent
from .models import GetV1MarineResponseCurrentUnits
from .models import GetV1MarineResponseDaily
from .models import GetV1MarineResponseDailyUnits
from .models import GetV1MarineResponseHourly
from .models import GetV1MarineResponseHourlyUnits
from .models import GetV1MarineResponseMinutely15
from .models import GetV1MarineResponseMinutely15Units
from .models import GetV1MarineTemperatureUnit
from .models import GetV1MarineTimeformat
from .models import GetV1MarineWindSpeedUnit
from .operations import GetV1Marine

__all__ = [
    "GetV1Marine",
    "GetV1MarineCellSelection",
    "GetV1MarineCurrentItem",
    "GetV1MarineDailyItem",
    "GetV1MarineHourlyItem",
    "GetV1MarineLengthUnit",
    "GetV1MarineMinutely15Item",
    "GetV1MarineModelsItem",
    "GetV1MarineResponse",
    "GetV1MarineResponseCurrent",
    "GetV1MarineResponseCurrentUnits",
    "GetV1MarineResponseDaily",
    "GetV1MarineResponseDailyUnits",
    "GetV1MarineResponseHourly",
    "GetV1MarineResponseHourlyUnits",
    "GetV1MarineResponseMinutely15",
    "GetV1MarineResponseMinutely15Units",
    "GetV1MarineTemperatureUnit",
    "GetV1MarineTimeformat",
    "GetV1MarineWindSpeedUnit",
    "MarineClient",
]
