# generated by action0-client-openapi v0.1.1 from flood.yml — do not edit
"""Typed API client for Open-Meteo Flood Forecast API 1.0."""

from .client import FloodClient
from .models import GetV1FloodCellSelection
from .models import GetV1FloodDailyItem
from .models import GetV1FloodModelsItem
from .models import GetV1FloodResponse
from .models import GetV1FloodResponseDaily
from .models import GetV1FloodResponseDailyUnits
from .models import GetV1FloodTimeformat
from .operations import GetV1Flood

__all__ = [
    "FloodClient",
    "GetV1Flood",
    "GetV1FloodCellSelection",
    "GetV1FloodDailyItem",
    "GetV1FloodModelsItem",
    "GetV1FloodResponse",
    "GetV1FloodResponseDaily",
    "GetV1FloodResponseDailyUnits",
    "GetV1FloodTimeformat",
]
