# generated by action0-client-openapi v0.1.2 from air-quality.yml — do not edit
"""Typed API client for Open-Meteo Air Quality API 1.0."""

from .client import AirQualityClient
from .errors import BadRequestError
from .models import GetV1AirQualityCurrentItem
from .models import GetV1AirQualityDomains
from .models import GetV1AirQualityError
from .models import GetV1AirQualityHourlyItem
from .models import GetV1AirQualityResponse
from .models import GetV1AirQualityResponseCurrent
from .models import GetV1AirQualityResponseCurrentUnits
from .models import GetV1AirQualityResponseHourly
from .models import GetV1AirQualityResponseHourlyUnits
from .models import GetV1AirQualityTimeformat
from .operations import GetV1AirQuality

__all__ = [
    "AirQualityClient",
    "BadRequestError",
    "GetV1AirQuality",
    "GetV1AirQualityCurrentItem",
    "GetV1AirQualityDomains",
    "GetV1AirQualityError",
    "GetV1AirQualityHourlyItem",
    "GetV1AirQualityResponse",
    "GetV1AirQualityResponseCurrent",
    "GetV1AirQualityResponseCurrentUnits",
    "GetV1AirQualityResponseHourly",
    "GetV1AirQualityResponseHourlyUnits",
    "GetV1AirQualityTimeformat",
]
