# generated by action0-client-openapi v0.1.2 from ensemble.yml — do not edit

from __future__ import annotations

from action0.client import APIClient
from action0.client import BackendT_co


class EnsembleClient(APIClient[BackendT_co]):
    """The Open-Meteo Ensemble Weather Forecast API API client."""

    def __init__(
        self,
        backend: BackendT_co,
        base_url: str = "https://ensemble-api.open-meteo.com",
    ) -> None:
        """
        :param backend: any sync, async or Twisted backend
        :param base_url: the API root
        """
        super().__init__(backend, base_url)
