# generated by action0-client-openapi v0.1.1 from historical-weather.yml — do not edit
"""Typed API client for Open-Meteo Historical Weather API 1.0."""

from .client import HistoricalWeatherClient
from .models import GetV1ArchiveCellSelection
from .models import GetV1ArchiveDailyItem
from .models import GetV1ArchiveHourlyItem
from .models import GetV1ArchiveModelsItem
from .models import GetV1ArchivePrecipitationUnit
from .models import GetV1ArchiveResponse
from .models import GetV1ArchiveResponseDaily
from .models import GetV1ArchiveResponseDailyUnits
from .models import GetV1ArchiveResponseHourly
from .models import GetV1ArchiveResponseHourlyUnits
from .models import GetV1ArchiveTemperatureUnit
from .models import GetV1ArchiveTimeformat
from .models import GetV1ArchiveWindSpeedUnit
from .operations import GetV1Archive

__all__ = [
    "GetV1Archive",
    "GetV1ArchiveCellSelection",
    "GetV1ArchiveDailyItem",
    "GetV1ArchiveHourlyItem",
    "GetV1ArchiveModelsItem",
    "GetV1ArchivePrecipitationUnit",
    "GetV1ArchiveResponse",
    "GetV1ArchiveResponseDaily",
    "GetV1ArchiveResponseDailyUnits",
    "GetV1ArchiveResponseHourly",
    "GetV1ArchiveResponseHourlyUnits",
    "GetV1ArchiveTemperatureUnit",
    "GetV1ArchiveTimeformat",
    "GetV1ArchiveWindSpeedUnit",
    "HistoricalWeatherClient",
]
