# generated by action0-client-openapi v0.1.1 from climate.yml — do not edit
"""Typed API client for Open-Meteo Climate Change API 1.0."""

from .client import ClimateClient
from .models import GetV1ClimateCellSelection
from .models import GetV1ClimateDailyItem
from .models import GetV1ClimateModelsItem
from .models import GetV1ClimatePrecipitationUnit
from .models import GetV1ClimateResponse
from .models import GetV1ClimateResponseDaily
from .models import GetV1ClimateResponseDailyUnits
from .models import GetV1ClimateTemperatureUnit
from .models import GetV1ClimateTimeformat
from .models import GetV1ClimateWindSpeedUnit
from .operations import GetV1Climate

__all__ = [
    "ClimateClient",
    "GetV1Climate",
    "GetV1ClimateCellSelection",
    "GetV1ClimateDailyItem",
    "GetV1ClimateModelsItem",
    "GetV1ClimatePrecipitationUnit",
    "GetV1ClimateResponse",
    "GetV1ClimateResponseDaily",
    "GetV1ClimateResponseDailyUnits",
    "GetV1ClimateTemperatureUnit",
    "GetV1ClimateTimeformat",
    "GetV1ClimateWindSpeedUnit",
]
