# generated by action0-client-openapi v0.1.2 from forecast.yml — do not edit
"""Typed API client for Open-Meteo Weather Forecast API 1.0."""

from .client import ForecastClient
from .errors import BadRequestError
from .models import GetV1ForecastCellSelection
from .models import GetV1ForecastCurrentItem
from .models import GetV1ForecastDailyItem
from .models import GetV1ForecastError
from .models import GetV1ForecastHourlyItem
from .models import GetV1ForecastMinutely15Item
from .models import GetV1ForecastModelsItem
from .models import GetV1ForecastPrecipitationUnit
from .models import GetV1ForecastResponse
from .models import GetV1ForecastResponseCurrent
from .models import GetV1ForecastResponseCurrentUnits
from .models import GetV1ForecastResponseDaily
from .models import GetV1ForecastResponseDailyUnits
from .models import GetV1ForecastResponseHourly
from .models import GetV1ForecastResponseHourlyUnits
from .models import GetV1ForecastResponseMinutely15
from .models import GetV1ForecastResponseMinutely15Units
from .models import GetV1ForecastTemperatureUnit
from .models import GetV1ForecastTimeformat
from .models import GetV1ForecastWindSpeedUnit
from .operations import GetV1Forecast

__all__ = [
    "BadRequestError",
    "ForecastClient",
    "GetV1Forecast",
    "GetV1ForecastCellSelection",
    "GetV1ForecastCurrentItem",
    "GetV1ForecastDailyItem",
    "GetV1ForecastError",
    "GetV1ForecastHourlyItem",
    "GetV1ForecastMinutely15Item",
    "GetV1ForecastModelsItem",
    "GetV1ForecastPrecipitationUnit",
    "GetV1ForecastResponse",
    "GetV1ForecastResponseCurrent",
    "GetV1ForecastResponseCurrentUnits",
    "GetV1ForecastResponseDaily",
    "GetV1ForecastResponseDailyUnits",
    "GetV1ForecastResponseHourly",
    "GetV1ForecastResponseHourlyUnits",
    "GetV1ForecastResponseMinutely15",
    "GetV1ForecastResponseMinutely15Units",
    "GetV1ForecastTemperatureUnit",
    "GetV1ForecastTimeformat",
    "GetV1ForecastWindSpeedUnit",
]
