# generated by action0-client-openapi v0.1.1 from seasonal.yml — do not edit
"""Typed API client for Open-Meteo Seasonal Weather Forecast API 1.0."""

from .client import SeasonalClient
from .models import GetV1SeasonalCellSelection
from .models import GetV1SeasonalDailyItem
from .models import GetV1SeasonalHourlyItem
from .models import GetV1SeasonalModelsItem
from .models import GetV1SeasonalMonthlyItem
from .models import GetV1SeasonalPrecipitationUnit
from .models import GetV1SeasonalResponse
from .models import GetV1SeasonalResponseDaily
from .models import GetV1SeasonalResponseDailyUnits
from .models import GetV1SeasonalResponseHourly
from .models import GetV1SeasonalResponseHourlyUnits
from .models import GetV1SeasonalResponseMonthly
from .models import GetV1SeasonalResponseMonthlyUnits
from .models import GetV1SeasonalResponseWeekly
from .models import GetV1SeasonalResponseWeeklyUnits
from .models import GetV1SeasonalTemperatureUnit
from .models import GetV1SeasonalTimeformat
from .models import GetV1SeasonalWeeklyItem
from .models import GetV1SeasonalWindSpeedUnit
from .operations import GetV1Seasonal

__all__ = [
    "GetV1Seasonal",
    "GetV1SeasonalCellSelection",
    "GetV1SeasonalDailyItem",
    "GetV1SeasonalHourlyItem",
    "GetV1SeasonalModelsItem",
    "GetV1SeasonalMonthlyItem",
    "GetV1SeasonalPrecipitationUnit",
    "GetV1SeasonalResponse",
    "GetV1SeasonalResponseDaily",
    "GetV1SeasonalResponseDailyUnits",
    "GetV1SeasonalResponseHourly",
    "GetV1SeasonalResponseHourlyUnits",
    "GetV1SeasonalResponseMonthly",
    "GetV1SeasonalResponseMonthlyUnits",
    "GetV1SeasonalResponseWeekly",
    "GetV1SeasonalResponseWeeklyUnits",
    "GetV1SeasonalTemperatureUnit",
    "GetV1SeasonalTimeformat",
    "GetV1SeasonalWeeklyItem",
    "GetV1SeasonalWindSpeedUnit",
    "SeasonalClient",
]
