# generated by action0-client-openapi v0.1.1 from seasonal.yml — do not edit

from __future__ import annotations

import enum
from dataclasses import dataclass
from typing import Any


class GetV1SeasonalHourlyItem(enum.Enum):
    """The ``GetV1SeasonalHourlyItem`` values."""

    TEMPERATURE_2M = "temperature_2m"
    DEW_POINT_2M = "dew_point_2m"
    PRESSURE_MSL = "pressure_msl"
    SEA_SURFACE_TEMPERATURE = "sea_surface_temperature"
    SNOWFALL_WATER_EQUIVALENT = "snowfall_water_equivalent"
    PRECIPITATION = "precipitation"
    SOIL_TEMPERATURE_0_TO_7CM = "soil_temperature_0_to_7cm"
    CLOUD_COVER = "cloud_cover"
    WIND_SPEED_10M = "wind_speed_10m"
    WIND_SPEED_100M = "wind_speed_100m"
    WIND_SPEED_200M = "wind_speed_200m"
    WIND_DIRECTION_10M = "wind_direction_10m"
    WIND_DIRECTION_100M = "wind_direction_100m"
    WIND_DIRECTION_200M = "wind_direction_200m"
    WIND_GUSTS_10M = "wind_gusts_10m"
    RAIN = "rain"
    SHOWERS = "showers"
    SNOWFALL = "snowfall"
    RELATIVE_HUMIDITY_2M = "relative_humidity_2m"
    APPARENT_TEMPERATURE = "apparent_temperature"
    ET0_FAO_EVAPOTRANSPIRATION = "et0_fao_evapotranspiration"
    VAPOUR_PRESSURE_DEFICIT = "vapour_pressure_deficit"
    WEATHER_CODE = "weather_code"
    SUNSHINE_DURATION = "sunshine_duration"
    WAVE_HEIGHT = "wave_height"
    WAVE_DIRECTION = "wave_direction"
    WAVE_PERIOD = "wave_period"
    WAVE_PEAK_PERIOD = "wave_peak_period"
    SOIL_TEMPERATURE_7_TO_28CM = "soil_temperature_7_to_28cm"
    SOIL_TEMPERATURE_28_TO_100CM = "soil_temperature_28_to_100cm"
    SOIL_TEMPERATURE_100_TO_255CM = "soil_temperature_100_to_255cm"
    SOIL_MOISTURE_0_TO_7CM = "soil_moisture_0_to_7cm"
    SOIL_MOISTURE_7_TO_28CM = "soil_moisture_7_to_28cm"
    SOIL_MOISTURE_28_TO_100CM = "soil_moisture_28_to_100cm"
    SOIL_MOISTURE_100_TO_255CM = "soil_moisture_100_to_255cm"
    SHORTWAVE_RADIATION = "shortwave_radiation"
    DIRECT_RADIATION = "direct_radiation"
    DIFFUSE_RADIATION = "diffuse_radiation"
    DIRECT_NORMAL_IRRADIANCE = "direct_normal_irradiance"
    GLOBAL_TILTED_IRRADIANCE = "global_tilted_irradiance"
    TERRESTRIAL_RADIATION = "terrestrial_radiation"
    SHORTWAVE_RADIATION_INSTANT = "shortwave_radiation_instant"
    DIRECT_RADIATION_INSTANT = "direct_radiation_instant"
    DIFFUSE_RADIATION_INSTANT = "diffuse_radiation_instant"
    DIRECT_NORMAL_IRRADIANCE_INSTANT = "direct_normal_irradiance_instant"
    GLOBAL_TILTED_IRRADIANCE_INSTANT = "global_tilted_irradiance_instant"
    TERRESTRIAL_RADIATION_INSTANT = "terrestrial_radiation_instant"


class GetV1SeasonalDailyItem(enum.Enum):
    """The ``GetV1SeasonalDailyItem`` values."""

    SUNRISE = "sunrise"
    SUNSET = "sunset"
    WEATHER_CODE = "weather_code"
    ET0_FAO_EVAPOTRANSPIRATION = "et0_fao_evapotranspiration"
    VAPOUR_PRESSURE_DEFICIT_MAX = "vapour_pressure_deficit_max"
    TEMPERATURE_2M_MAX = "temperature_2m_max"
    TEMPERATURE_2M_MIN = "temperature_2m_min"
    TEMPERATURE_2M_MEAN = "temperature_2m_mean"
    SUNSHINE_DURATION = "sunshine_duration"
    DEW_POINT_2M_MEAN = "dew_point_2m_mean"
    PRESSURE_MSL_MEAN = "pressure_msl_mean"
    SEA_SURFACE_TEMPERATURE_MEAN = "sea_surface_temperature_mean"
    CLOUD_COVER_MEAN = "cloud_cover_mean"
    WIND_SPEED_10M_MEAN = "wind_speed_10m_mean"
    WIND_SPEED_100M_MEAN = "wind_speed_100m_mean"
    SNOW_DEPTH_MEAN = "snow_depth_mean"
    SOIL_TEMPERATURE_0_TO_7CM_MEAN = "soil_temperature_0_to_7cm_mean"


class GetV1SeasonalWeeklyItem(enum.Enum):
    """The ``GetV1SeasonalWeeklyItem`` values."""

    WIND_SPEED_10M_MEAN = "wind_speed_10m_mean"
    WIND_SPEED_10M_ANOMALY = "wind_speed_10m_anomaly"
    WIND_SPEED_100M_MEAN = "wind_speed_100m_mean"
    WIND_SPEED_100M_ANOMALY = "wind_speed_100m_anomaly"
    WIND_DIRECTION_10M_MEAN = "wind_direction_10m_mean"
    WIND_DIRECTION_10M_ANOMALY = "wind_direction_10m_anomaly"
    WIND_DIRECTION_100M_MEAN = "wind_direction_100m_mean"
    WIND_DIRECTION_100M_ANOMALY = "wind_direction_100m_anomaly"
    SNOW_DEPTH_MEAN = "snow_depth_mean"
    SNOW_DEPTH_ANOMALY = "snow_depth_anomaly"
    SNOWFALL_MEAN = "snowfall_mean"
    SNOWFALL_ANOMALY = "snowfall_anomaly"
    TEMPERATURE_2M_ANOMALY_GT0 = "temperature_2m_anomaly_gt0"
    TEMPERATURE_2M_ANOMALY_GT1 = "temperature_2m_anomaly_gt1"
    TEMPERATURE_2M_ANOMALY_GT2 = "temperature_2m_anomaly_gt2"
    TEMPERATURE_2M_ANOMALY_LTM1 = "temperature_2m_anomaly_ltm1"
    TEMPERATURE_2M_ANOMALY_LTM2 = "temperature_2m_anomaly_ltm2"
    PRESSURE_MSL_ANOMALY_GT0 = "pressure_msl_anomaly_gt0"
    SURFACE_TEMPERATURE_ANOMALY_GT0 = "surface_temperature_anomaly_gt0"
    PRECIPITATION_ANOMALY_GT0 = "precipitation_anomaly_gt0"
    PRECIPITATION_ANOMALY_GT10 = "precipitation_anomaly_gt10"
    PRECIPITATION_ANOMALY_GT20 = "precipitation_anomaly_gt20"
    TEMPERATURE_2M_SOT10 = "temperature_2m_sot10"
    TEMPERATURE_2M_SOT90 = "temperature_2m_sot90"
    TEMPERATURE_2M_EFI = "temperature_2m_efi"
    PRECIPITATION_EFI = "precipitation_efi"
    PRECIPITATION_SOT90 = "precipitation_sot90"
    SHOWERS_MEAN = "showers_mean"
    SNOW_DENSITY_MEAN = "snow_density_mean"
    SNOW_DENSITY_ANOMALY = "snow_density_anomaly"
    SNOW_DEPTH_WATER_EQUIVALENT_MEAN = "snow_depth_water_equivalent_mean"
    SNOW_DEPTH_WATER_EQUIVALENT_ANOMALY = "snow_depth_water_equivalent_anomaly"
    TOTAL_COLUMN_INTEGRATED_WATER_VAPOUR_MEAN = "total_column_integrated_water_vapour_mean"
    TOTAL_COLUMN_INTEGRATED_WATER_VAPOUR_ANOMALY = "total_column_integrated_water_vapour_anomaly"
    TEMPERATURE_2M_MEAN = "temperature_2m_mean"
    TEMPERATURE_2M_ANOMALY = "temperature_2m_anomaly"
    DEW_POINT_2M_MEAN = "dew_point_2m_mean"
    DEW_POINT_2M_ANOMALY = "dew_point_2m_anomaly"
    PRESSURE_MSL_MEAN = "pressure_msl_mean"
    PRESSURE_MSL_ANOMALY = "pressure_msl_anomaly"
    SEA_SURFACE_TEMPERATURE_MEAN = "sea_surface_temperature_mean"
    SEA_SURFACE_TEMPERATURE_ANOMALY = "sea_surface_temperature_anomaly"
    WIND_U_COMPONENT_10M_MEAN = "wind_u_component_10m_mean"
    WIND_U_COMPONENT_10M_ANOMALY = "wind_u_component_10m_anomaly"
    WIND_V_COMPONENT_10M_MEAN = "wind_v_component_10m_mean"
    WIND_V_COMPONENT_10M_ANOMALY = "wind_v_component_10m_anomaly"
    WIND_U_COMPONENT_100M_MEAN = "wind_u_component_100m_mean"
    WIND_U_COMPONENT_100M_ANOMALY = "wind_u_component_100m_anomaly"
    WIND_V_COMPONENT_100M_MEAN = "wind_v_component_100m_mean"
    WIND_V_COMPONENT_100M_ANOMALY = "wind_v_component_100m_anomaly"
    SNOWFALL_WATER_EQUIVALENT_MEAN = "snowfall_water_equivalent_mean"
    SNOWFALL_WATER_EQUIVALENT_ANOMALY = "snowfall_water_equivalent_anomaly"
    PRECIPITATION_MEAN = "precipitation_mean"
    PRECIPITATION_ANOMALY = "precipitation_anomaly"
    CLOUD_COVER_MEAN = "cloud_cover_mean"
    CLOUD_COVER_ANOMALY = "cloud_cover_anomaly"
    SUNSHINE_DURATION_MEAN = "sunshine_duration_mean"
    SUNSHINE_DURATION_ANOMALY = "sunshine_duration_anomaly"
    SOIL_TEMPERATURE_0_TO_7CM_MEAN = "soil_temperature_0_to_7cm_mean"
    SOIL_TEMPERATURE_0_TO_7CM_ANOMALY = "soil_temperature_0_to_7cm_anomaly"
    TEMPERATURE_MAX6H_2M_MEAN = "temperature_max6h_2m_mean"
    TEMPERATURE_MAX6H_2M_ANOMALY = "temperature_max6h_2m_anomaly"
    TEMPERATURE_MIN6H_2M_MEAN = "temperature_min6h_2m_mean"
    TEMPERATURE_MIN6H_2M_ANOMALY = "temperature_min6h_2m_anomaly"


class GetV1SeasonalMonthlyItem(enum.Enum):
    """The ``GetV1SeasonalMonthlyItem`` values."""

    WIND_GUSTS_10M_ANOMALY = "wind_gusts_10m_anomaly"
    WIND_SPEED_10M_MEAN = "wind_speed_10m_mean"
    WIND_SPEED_10M_ANOMALY = "wind_speed_10m_anomaly"
    ALBEDO_MEAN = "albedo_mean"
    ALBEDO_ANOMALY = "albedo_anomaly"
    CLOUD_COVER_LOW_MEAN = "cloud_cover_low_mean"
    CLOUD_COVER_LOW_ANOMALY = "cloud_cover_low_anomaly"
    SHOWERS_MEAN = "showers_mean"
    SHOWERS_ANOMALY = "showers_anomaly"
    RUNOFF_MEAN = "runoff_mean"
    RUNOFF_ANOMALY = "runoff_anomaly"
    SNOW_DENSITY_MEAN = "snow_density_mean"
    SNOW_DENSITY_ANOMALY = "snow_density_anomaly"
    SNOW_DEPTH_WATER_EQUIVALENT_MEAN = "snow_depth_water_equivalent_mean"
    SNOW_DEPTH_WATER_EQUIVALENT_ANOMALY = "snow_depth_water_equivalent_anomaly"
    TOTAL_COLUMN_INTEGRATED_WATER_VAPOUR_MEAN = "total_column_integrated_water_vapour_mean"
    TOTAL_COLUMN_INTEGRATED_WATER_VAPOUR_ANOMALY = "total_column_integrated_water_vapour_anomaly"
    TEMPERATURE_2M_MEAN = "temperature_2m_mean"
    TEMPERATURE_2M_ANOMALY = "temperature_2m_anomaly"
    DEW_POINT_2M_MEAN = "dew_point_2m_mean"
    DEW_POINT_2M_ANOMALY = "dew_point_2m_anomaly"
    PRESSURE_MSL_MEAN = "pressure_msl_mean"
    PRESSURE_MSL_ANOMALY = "pressure_msl_anomaly"
    SEA_SURFACE_TEMPERATURE_MEAN = "sea_surface_temperature_mean"
    SEA_SURFACE_TEMPERATURE_ANOMALY = "sea_surface_temperature_anomaly"
    WIND_U_COMPONENT_10M_MEAN = "wind_u_component_10m_mean"
    WIND_U_COMPONENT_10M_ANOMALY = "wind_u_component_10m_anomaly"
    WIND_V_COMPONENT_10M_MEAN = "wind_v_component_10m_mean"
    WIND_V_COMPONENT_10M_ANOMALY = "wind_v_component_10m_anomaly"
    SNOWFALL_WATER_EQUIVALENT_MEAN = "snowfall_water_equivalent_mean"
    SNOWFALL_WATER_EQUIVALENT_ANOMALY = "snowfall_water_equivalent_anomaly"
    PRECIPITATION_MEAN = "precipitation_mean"
    PRECIPITATION_ANOMALY = "precipitation_anomaly"
    SHORTWAVE_RADIATION_MEAN = "shortwave_radiation_mean"
    SHORTWAVE_RADIATION_ANOMALY = "shortwave_radiation_anomaly"
    LONGWAVE_RADIATION_MEAN = "longwave_radiation_mean"
    LONGWAVE_RADIATION_ANOMALY = "longwave_radiation_anomaly"
    CLOUD_COVER_MEAN = "cloud_cover_mean"
    CLOUD_COVER_ANOMALY = "cloud_cover_anomaly"
    SUNSHINE_DURATION_MEAN = "sunshine_duration_mean"
    SUNSHINE_DURATION_ANOMALY = "sunshine_duration_anomaly"
    SOIL_TEMPERATURE_0_TO_7CM_MEAN = "soil_temperature_0_to_7cm_mean"
    SOIL_TEMPERATURE_0_TO_7CM_ANOMALY = "soil_temperature_0_to_7cm_anomaly"
    SOIL_TEMPERATURE_7_TO_28CM_MEAN = "soil_temperature_7_to_28cm_mean"
    SOIL_TEMPERATURE_7_TO_28CM_ANOMALY = "soil_temperature_7_to_28cm_anomaly"
    SOIL_TEMPERATURE_28_TO_100CM_MEAN = "soil_temperature_28_to_100cm_mean"
    SOIL_TEMPERATURE_28_TO_100CM_ANOMALY = "soil_temperature_28_to_100cm_anomaly"
    SOIL_TEMPERATURE_100_TO_255CM_MEAN = "soil_temperature_100_to_255cm_mean"
    SOIL_TEMPERATURE_100_TO_255CM_ANOMALY = "soil_temperature_100_to_255cm_anomaly"
    SOIL_MOISTURE_0_TO_7CM_MEAN = "soil_moisture_0_to_7cm_mean"
    SOIL_MOISTURE_0_TO_7CM_ANOMALY = "soil_moisture_0_to_7cm_anomaly"
    SOIL_MOISTURE_7_TO_28CM_MEAN = "soil_moisture_7_to_28cm_mean"
    SOIL_MOISTURE_7_TO_28CM_ANOMALY = "soil_moisture_7_to_28cm_anomaly"
    SOIL_MOISTURE_28_TO_100CM_MEAN = "soil_moisture_28_to_100cm_mean"
    SOIL_MOISTURE_28_TO_100CM_ANOMALY = "soil_moisture_28_to_100cm_anomaly"
    SOIL_MOISTURE_100_TO_255CM_MEAN = "soil_moisture_100_to_255cm_mean"
    SOIL_MOISTURE_100_TO_255CM_ANOMALY = "soil_moisture_100_to_255cm_anomaly"
    TEMPERATURE_MAX24H_2M_MEAN = "temperature_max24h_2m_mean"
    TEMPERATURE_MAX24H_2M_ANOMALY = "temperature_max24h_2m_anomaly"
    TEMPERATURE_MIN24H_2M_MEAN = "temperature_min24h_2m_mean"
    TEMPERATURE_MIN24H_2M_ANOMALY = "temperature_min24h_2m_anomaly"
    SEA_ICE_COVER_MEAN = "sea_ice_cover_mean"
    SEA_ICE_COVER_ANOMALY = "sea_ice_cover_anomaly"
    LATENT_HEAT_FLUX_MEAN = "latent_heat_flux_mean"
    LATENT_HEAT_FLUX_ANOMALY = "latent_heat_flux_anomaly"
    SENSIBLE_HEAT_FLUX_MEAN = "sensible_heat_flux_mean"
    SENSIBLE_HEAT_FLUX_ANOMALY = "sensible_heat_flux_anomaly"
    EVAPOTRANSPIRATION_MEAN = "evapotranspiration_mean"
    EVAPOTRANSPIRATION_ANOMALY = "evapotranspiration_anomaly"
    SNOWFALL_MEAN = "snowfall_mean"
    SNOWFALL_ANOMALY = "snowfall_anomaly"
    SNOW_DEPTH_MEAN = "snow_depth_mean"
    SNOW_DEPTH_ANOMALY = "snow_depth_anomaly"


class GetV1SeasonalTemperatureUnit(enum.Enum):
    """The ``GetV1SeasonalTemperatureUnit`` values."""

    CELSIUS = "celsius"
    FAHRENHEIT = "fahrenheit"


class GetV1SeasonalWindSpeedUnit(enum.Enum):
    """The ``GetV1SeasonalWindSpeedUnit`` values."""

    KMH = "kmh"
    MS = "ms"
    MPH = "mph"
    KN = "kn"


class GetV1SeasonalPrecipitationUnit(enum.Enum):
    """The ``GetV1SeasonalPrecipitationUnit`` values."""

    MM = "mm"
    INCH = "inch"


class GetV1SeasonalTimeformat(enum.Enum):
    """The ``GetV1SeasonalTimeformat`` values."""

    ISO8601 = "iso8601"
    UNIXTIME = "unixtime"


class GetV1SeasonalCellSelection(enum.Enum):
    """The ``GetV1SeasonalCellSelection`` values."""

    LAND = "land"
    SEA = "sea"
    NEAREST = "nearest"


class GetV1SeasonalModelsItem(enum.Enum):
    """The ``GetV1SeasonalModelsItem`` values."""

    BEST_MATCH = "best_match"
    ECMWF_SEASONAL_SEAMLESS = "ecmwf_seasonal_seamless"
    ECMWF_SEAS5 = "ecmwf_seas5"
    ECMWF_EC46 = "ecmwf_ec46"
    ECMWF_SEASONAL_ENSEMBLE_MEAN_SEAMLESS = "ecmwf_seasonal_ensemble_mean_seamless"
    ECMWF_SEAS5_ENSEMBLE_MEAN = "ecmwf_seas5_ensemble_mean"
    ECMWF_EC46_ENSEMBLE_MEAN = "ecmwf_ec46_ensemble_mean"


@dataclass
class GetV1SeasonalResponseHourly:
    """The ``GetV1SeasonalResponseHourly`` model."""

    time: list[str] | None = None
    #: The payload keys not declared under properties.
    additional_properties: dict[str, list[float]] | None = None


# payload keys outside this set land in additional_properties
_GET_V1_SEASONAL_RESPONSE_HOURLY_PROPERTIES = {"time"}


def get_v1_seasonal_response_hourly_from_json(data: Any) -> GetV1SeasonalResponseHourly:
    """
    Build a :py:class:`GetV1SeasonalResponseHourly` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the GetV1SeasonalResponseHourly
    """
    return GetV1SeasonalResponseHourly(
        time=data.get("time"),
        additional_properties=(
            {
                key: value
                for key, value in data.items()
                if key not in _GET_V1_SEASONAL_RESPONSE_HOURLY_PROPERTIES
            }
        ),
    )


@dataclass
class GetV1SeasonalResponseHourlyUnits:
    """The ``GetV1SeasonalResponseHourlyUnits`` model."""

    time: str | None = None
    #: The payload keys not declared under properties.
    additional_properties: dict[str, str] | None = None


# payload keys outside this set land in additional_properties
_GET_V1_SEASONAL_RESPONSE_HOURLY_UNITS_PROPERTIES = {"time"}


def get_v1_seasonal_response_hourly_units_from_json(data: Any) -> GetV1SeasonalResponseHourlyUnits:
    """
    Build a :py:class:`GetV1SeasonalResponseHourlyUnits` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the GetV1SeasonalResponseHourlyUnits
    """
    return GetV1SeasonalResponseHourlyUnits(
        time=data.get("time"),
        additional_properties=(
            {
                key: value
                for key, value in data.items()
                if key not in _GET_V1_SEASONAL_RESPONSE_HOURLY_UNITS_PROPERTIES
            }
        ),
    )


@dataclass
class GetV1SeasonalResponseDaily:
    """The ``GetV1SeasonalResponseDaily`` model."""

    time: list[str] | None = None
    #: The payload keys not declared under properties.
    additional_properties: dict[str, list[float]] | None = None


# payload keys outside this set land in additional_properties
_GET_V1_SEASONAL_RESPONSE_DAILY_PROPERTIES = {"time"}


def get_v1_seasonal_response_daily_from_json(data: Any) -> GetV1SeasonalResponseDaily:
    """
    Build a :py:class:`GetV1SeasonalResponseDaily` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the GetV1SeasonalResponseDaily
    """
    return GetV1SeasonalResponseDaily(
        time=data.get("time"),
        additional_properties=(
            {
                key: value
                for key, value in data.items()
                if key not in _GET_V1_SEASONAL_RESPONSE_DAILY_PROPERTIES
            }
        ),
    )


@dataclass
class GetV1SeasonalResponseDailyUnits:
    """The ``GetV1SeasonalResponseDailyUnits`` model."""

    time: str | None = None
    #: The payload keys not declared under properties.
    additional_properties: dict[str, str] | None = None


# payload keys outside this set land in additional_properties
_GET_V1_SEASONAL_RESPONSE_DAILY_UNITS_PROPERTIES = {"time"}


def get_v1_seasonal_response_daily_units_from_json(data: Any) -> GetV1SeasonalResponseDailyUnits:
    """
    Build a :py:class:`GetV1SeasonalResponseDailyUnits` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the GetV1SeasonalResponseDailyUnits
    """
    return GetV1SeasonalResponseDailyUnits(
        time=data.get("time"),
        additional_properties=(
            {
                key: value
                for key, value in data.items()
                if key not in _GET_V1_SEASONAL_RESPONSE_DAILY_UNITS_PROPERTIES
            }
        ),
    )


@dataclass
class GetV1SeasonalResponseWeekly:
    """The ``GetV1SeasonalResponseWeekly`` model."""

    time: list[str] | None = None
    wind_speed_10m_mean: list[float] | None = None
    wind_speed_10m_anomaly: list[float] | None = None
    wind_speed_100m_mean: list[float] | None = None
    wind_speed_100m_anomaly: list[float] | None = None
    wind_direction_10m_mean: list[float] | None = None
    wind_direction_10m_anomaly: list[float] | None = None
    wind_direction_100m_mean: list[float] | None = None
    wind_direction_100m_anomaly: list[float] | None = None
    snow_depth_mean: list[float] | None = None
    snow_depth_anomaly: list[float] | None = None
    snowfall_mean: list[float] | None = None
    snowfall_anomaly: list[float] | None = None
    temperature_2m_anomaly_gt0: list[float] | None = None
    temperature_2m_anomaly_gt1: list[float] | None = None
    temperature_2m_anomaly_gt2: list[float] | None = None
    temperature_2m_anomaly_ltm1: list[float] | None = None
    temperature_2m_anomaly_ltm2: list[float] | None = None
    pressure_msl_anomaly_gt0: list[float] | None = None
    surface_temperature_anomaly_gt0: list[float] | None = None
    precipitation_anomaly_gt0: list[float] | None = None
    precipitation_anomaly_gt10: list[float] | None = None
    precipitation_anomaly_gt20: list[float] | None = None
    temperature_2m_sot10: list[float] | None = None
    temperature_2m_sot90: list[float] | None = None
    temperature_2m_efi: list[float] | None = None
    precipitation_efi: list[float] | None = None
    precipitation_sot90: list[float] | None = None
    showers_mean: list[float] | None = None
    snow_density_mean: list[float] | None = None
    snow_density_anomaly: list[float] | None = None
    snow_depth_water_equivalent_mean: list[float] | None = None
    snow_depth_water_equivalent_anomaly: list[float] | None = None
    total_column_integrated_water_vapour_mean: list[float] | None = None
    total_column_integrated_water_vapour_anomaly: list[float] | None = None
    temperature_2m_mean: list[float] | None = None
    temperature_2m_anomaly: list[float] | None = None
    dew_point_2m_mean: list[float] | None = None
    dew_point_2m_anomaly: list[float] | None = None
    pressure_msl_mean: list[float] | None = None
    pressure_msl_anomaly: list[float] | None = None
    sea_surface_temperature_mean: list[float] | None = None
    sea_surface_temperature_anomaly: list[float] | None = None
    wind_u_component_10m_mean: list[float] | None = None
    wind_u_component_10m_anomaly: list[float] | None = None
    wind_v_component_10m_mean: list[float] | None = None
    wind_v_component_10m_anomaly: list[float] | None = None
    wind_u_component_100m_mean: list[float] | None = None
    wind_u_component_100m_anomaly: list[float] | None = None
    wind_v_component_100m_mean: list[float] | None = None
    wind_v_component_100m_anomaly: list[float] | None = None
    snowfall_water_equivalent_mean: list[float] | None = None
    snowfall_water_equivalent_anomaly: list[float] | None = None
    precipitation_mean: list[float] | None = None
    precipitation_anomaly: list[float] | None = None
    cloud_cover_mean: list[float] | None = None
    cloud_cover_anomaly: list[float] | None = None
    sunshine_duration_mean: list[float] | None = None
    sunshine_duration_anomaly: list[float] | None = None
    soil_temperature_0_to_7cm_mean: list[float] | None = None
    soil_temperature_0_to_7cm_anomaly: list[float] | None = None
    temperature_max6h_2m_mean: list[float] | None = None
    temperature_max6h_2m_anomaly: list[float] | None = None
    temperature_min6h_2m_mean: list[float] | None = None
    temperature_min6h_2m_anomaly: list[float] | None = None


def get_v1_seasonal_response_weekly_from_json(data: Any) -> GetV1SeasonalResponseWeekly:
    """
    Build a :py:class:`GetV1SeasonalResponseWeekly` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the GetV1SeasonalResponseWeekly
    """
    return GetV1SeasonalResponseWeekly(
        time=data.get("time"),
        wind_speed_10m_mean=data.get("wind_speed_10m_mean"),
        wind_speed_10m_anomaly=data.get("wind_speed_10m_anomaly"),
        wind_speed_100m_mean=data.get("wind_speed_100m_mean"),
        wind_speed_100m_anomaly=data.get("wind_speed_100m_anomaly"),
        wind_direction_10m_mean=data.get("wind_direction_10m_mean"),
        wind_direction_10m_anomaly=data.get("wind_direction_10m_anomaly"),
        wind_direction_100m_mean=data.get("wind_direction_100m_mean"),
        wind_direction_100m_anomaly=data.get("wind_direction_100m_anomaly"),
        snow_depth_mean=data.get("snow_depth_mean"),
        snow_depth_anomaly=data.get("snow_depth_anomaly"),
        snowfall_mean=data.get("snowfall_mean"),
        snowfall_anomaly=data.get("snowfall_anomaly"),
        temperature_2m_anomaly_gt0=data.get("temperature_2m_anomaly_gt0"),
        temperature_2m_anomaly_gt1=data.get("temperature_2m_anomaly_gt1"),
        temperature_2m_anomaly_gt2=data.get("temperature_2m_anomaly_gt2"),
        temperature_2m_anomaly_ltm1=data.get("temperature_2m_anomaly_ltm1"),
        temperature_2m_anomaly_ltm2=data.get("temperature_2m_anomaly_ltm2"),
        pressure_msl_anomaly_gt0=data.get("pressure_msl_anomaly_gt0"),
        surface_temperature_anomaly_gt0=data.get("surface_temperature_anomaly_gt0"),
        precipitation_anomaly_gt0=data.get("precipitation_anomaly_gt0"),
        precipitation_anomaly_gt10=data.get("precipitation_anomaly_gt10"),
        precipitation_anomaly_gt20=data.get("precipitation_anomaly_gt20"),
        temperature_2m_sot10=data.get("temperature_2m_sot10"),
        temperature_2m_sot90=data.get("temperature_2m_sot90"),
        temperature_2m_efi=data.get("temperature_2m_efi"),
        precipitation_efi=data.get("precipitation_efi"),
        precipitation_sot90=data.get("precipitation_sot90"),
        showers_mean=data.get("showers_mean"),
        snow_density_mean=data.get("snow_density_mean"),
        snow_density_anomaly=data.get("snow_density_anomaly"),
        snow_depth_water_equivalent_mean=data.get("snow_depth_water_equivalent_mean"),
        snow_depth_water_equivalent_anomaly=data.get("snow_depth_water_equivalent_anomaly"),
        total_column_integrated_water_vapour_mean=(
            data.get("total_column_integrated_water_vapour_mean")
        ),
        total_column_integrated_water_vapour_anomaly=(
            data.get("total_column_integrated_water_vapour_anomaly")
        ),
        temperature_2m_mean=data.get("temperature_2m_mean"),
        temperature_2m_anomaly=data.get("temperature_2m_anomaly"),
        dew_point_2m_mean=data.get("dew_point_2m_mean"),
        dew_point_2m_anomaly=data.get("dew_point_2m_anomaly"),
        pressure_msl_mean=data.get("pressure_msl_mean"),
        pressure_msl_anomaly=data.get("pressure_msl_anomaly"),
        sea_surface_temperature_mean=data.get("sea_surface_temperature_mean"),
        sea_surface_temperature_anomaly=data.get("sea_surface_temperature_anomaly"),
        wind_u_component_10m_mean=data.get("wind_u_component_10m_mean"),
        wind_u_component_10m_anomaly=data.get("wind_u_component_10m_anomaly"),
        wind_v_component_10m_mean=data.get("wind_v_component_10m_mean"),
        wind_v_component_10m_anomaly=data.get("wind_v_component_10m_anomaly"),
        wind_u_component_100m_mean=data.get("wind_u_component_100m_mean"),
        wind_u_component_100m_anomaly=data.get("wind_u_component_100m_anomaly"),
        wind_v_component_100m_mean=data.get("wind_v_component_100m_mean"),
        wind_v_component_100m_anomaly=data.get("wind_v_component_100m_anomaly"),
        snowfall_water_equivalent_mean=data.get("snowfall_water_equivalent_mean"),
        snowfall_water_equivalent_anomaly=data.get("snowfall_water_equivalent_anomaly"),
        precipitation_mean=data.get("precipitation_mean"),
        precipitation_anomaly=data.get("precipitation_anomaly"),
        cloud_cover_mean=data.get("cloud_cover_mean"),
        cloud_cover_anomaly=data.get("cloud_cover_anomaly"),
        sunshine_duration_mean=data.get("sunshine_duration_mean"),
        sunshine_duration_anomaly=data.get("sunshine_duration_anomaly"),
        soil_temperature_0_to_7cm_mean=data.get("soil_temperature_0_to_7cm_mean"),
        soil_temperature_0_to_7cm_anomaly=data.get("soil_temperature_0_to_7cm_anomaly"),
        temperature_max6h_2m_mean=data.get("temperature_max6h_2m_mean"),
        temperature_max6h_2m_anomaly=data.get("temperature_max6h_2m_anomaly"),
        temperature_min6h_2m_mean=data.get("temperature_min6h_2m_mean"),
        temperature_min6h_2m_anomaly=data.get("temperature_min6h_2m_anomaly"),
    )


@dataclass
class GetV1SeasonalResponseWeeklyUnits:
    """The ``GetV1SeasonalResponseWeeklyUnits`` model."""

    time: str | None = None
    wind_speed_10m_mean: str | None = None
    wind_speed_10m_anomaly: str | None = None
    wind_speed_100m_mean: str | None = None
    wind_speed_100m_anomaly: str | None = None
    wind_direction_10m_mean: str | None = None
    wind_direction_10m_anomaly: str | None = None
    wind_direction_100m_mean: str | None = None
    wind_direction_100m_anomaly: str | None = None
    snow_depth_mean: str | None = None
    snow_depth_anomaly: str | None = None
    snowfall_mean: str | None = None
    snowfall_anomaly: str | None = None
    temperature_2m_anomaly_gt0: str | None = None
    temperature_2m_anomaly_gt1: str | None = None
    temperature_2m_anomaly_gt2: str | None = None
    temperature_2m_anomaly_ltm1: str | None = None
    temperature_2m_anomaly_ltm2: str | None = None
    pressure_msl_anomaly_gt0: str | None = None
    surface_temperature_anomaly_gt0: str | None = None
    precipitation_anomaly_gt0: str | None = None
    precipitation_anomaly_gt10: str | None = None
    precipitation_anomaly_gt20: str | None = None
    temperature_2m_sot10: str | None = None
    temperature_2m_sot90: str | None = None
    temperature_2m_efi: str | None = None
    precipitation_efi: str | None = None
    precipitation_sot90: str | None = None
    showers_mean: str | None = None
    snow_density_mean: str | None = None
    snow_density_anomaly: str | None = None
    snow_depth_water_equivalent_mean: str | None = None
    snow_depth_water_equivalent_anomaly: str | None = None
    total_column_integrated_water_vapour_mean: str | None = None
    total_column_integrated_water_vapour_anomaly: str | None = None
    temperature_2m_mean: str | None = None
    temperature_2m_anomaly: str | None = None
    dew_point_2m_mean: str | None = None
    dew_point_2m_anomaly: str | None = None
    pressure_msl_mean: str | None = None
    pressure_msl_anomaly: str | None = None
    sea_surface_temperature_mean: str | None = None
    sea_surface_temperature_anomaly: str | None = None
    wind_u_component_10m_mean: str | None = None
    wind_u_component_10m_anomaly: str | None = None
    wind_v_component_10m_mean: str | None = None
    wind_v_component_10m_anomaly: str | None = None
    wind_u_component_100m_mean: str | None = None
    wind_u_component_100m_anomaly: str | None = None
    wind_v_component_100m_mean: str | None = None
    wind_v_component_100m_anomaly: str | None = None
    snowfall_water_equivalent_mean: str | None = None
    snowfall_water_equivalent_anomaly: str | None = None
    precipitation_mean: str | None = None
    precipitation_anomaly: str | None = None
    cloud_cover_mean: str | None = None
    cloud_cover_anomaly: str | None = None
    sunshine_duration_mean: str | None = None
    sunshine_duration_anomaly: str | None = None
    soil_temperature_0_to_7cm_mean: str | None = None
    soil_temperature_0_to_7cm_anomaly: str | None = None
    temperature_max6h_2m_mean: str | None = None
    temperature_max6h_2m_anomaly: str | None = None
    temperature_min6h_2m_mean: str | None = None
    temperature_min6h_2m_anomaly: str | None = None


def get_v1_seasonal_response_weekly_units_from_json(data: Any) -> GetV1SeasonalResponseWeeklyUnits:
    """
    Build a :py:class:`GetV1SeasonalResponseWeeklyUnits` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the GetV1SeasonalResponseWeeklyUnits
    """
    return GetV1SeasonalResponseWeeklyUnits(
        time=data.get("time"),
        wind_speed_10m_mean=data.get("wind_speed_10m_mean"),
        wind_speed_10m_anomaly=data.get("wind_speed_10m_anomaly"),
        wind_speed_100m_mean=data.get("wind_speed_100m_mean"),
        wind_speed_100m_anomaly=data.get("wind_speed_100m_anomaly"),
        wind_direction_10m_mean=data.get("wind_direction_10m_mean"),
        wind_direction_10m_anomaly=data.get("wind_direction_10m_anomaly"),
        wind_direction_100m_mean=data.get("wind_direction_100m_mean"),
        wind_direction_100m_anomaly=data.get("wind_direction_100m_anomaly"),
        snow_depth_mean=data.get("snow_depth_mean"),
        snow_depth_anomaly=data.get("snow_depth_anomaly"),
        snowfall_mean=data.get("snowfall_mean"),
        snowfall_anomaly=data.get("snowfall_anomaly"),
        temperature_2m_anomaly_gt0=data.get("temperature_2m_anomaly_gt0"),
        temperature_2m_anomaly_gt1=data.get("temperature_2m_anomaly_gt1"),
        temperature_2m_anomaly_gt2=data.get("temperature_2m_anomaly_gt2"),
        temperature_2m_anomaly_ltm1=data.get("temperature_2m_anomaly_ltm1"),
        temperature_2m_anomaly_ltm2=data.get("temperature_2m_anomaly_ltm2"),
        pressure_msl_anomaly_gt0=data.get("pressure_msl_anomaly_gt0"),
        surface_temperature_anomaly_gt0=data.get("surface_temperature_anomaly_gt0"),
        precipitation_anomaly_gt0=data.get("precipitation_anomaly_gt0"),
        precipitation_anomaly_gt10=data.get("precipitation_anomaly_gt10"),
        precipitation_anomaly_gt20=data.get("precipitation_anomaly_gt20"),
        temperature_2m_sot10=data.get("temperature_2m_sot10"),
        temperature_2m_sot90=data.get("temperature_2m_sot90"),
        temperature_2m_efi=data.get("temperature_2m_efi"),
        precipitation_efi=data.get("precipitation_efi"),
        precipitation_sot90=data.get("precipitation_sot90"),
        showers_mean=data.get("showers_mean"),
        snow_density_mean=data.get("snow_density_mean"),
        snow_density_anomaly=data.get("snow_density_anomaly"),
        snow_depth_water_equivalent_mean=data.get("snow_depth_water_equivalent_mean"),
        snow_depth_water_equivalent_anomaly=data.get("snow_depth_water_equivalent_anomaly"),
        total_column_integrated_water_vapour_mean=(
            data.get("total_column_integrated_water_vapour_mean")
        ),
        total_column_integrated_water_vapour_anomaly=(
            data.get("total_column_integrated_water_vapour_anomaly")
        ),
        temperature_2m_mean=data.get("temperature_2m_mean"),
        temperature_2m_anomaly=data.get("temperature_2m_anomaly"),
        dew_point_2m_mean=data.get("dew_point_2m_mean"),
        dew_point_2m_anomaly=data.get("dew_point_2m_anomaly"),
        pressure_msl_mean=data.get("pressure_msl_mean"),
        pressure_msl_anomaly=data.get("pressure_msl_anomaly"),
        sea_surface_temperature_mean=data.get("sea_surface_temperature_mean"),
        sea_surface_temperature_anomaly=data.get("sea_surface_temperature_anomaly"),
        wind_u_component_10m_mean=data.get("wind_u_component_10m_mean"),
        wind_u_component_10m_anomaly=data.get("wind_u_component_10m_anomaly"),
        wind_v_component_10m_mean=data.get("wind_v_component_10m_mean"),
        wind_v_component_10m_anomaly=data.get("wind_v_component_10m_anomaly"),
        wind_u_component_100m_mean=data.get("wind_u_component_100m_mean"),
        wind_u_component_100m_anomaly=data.get("wind_u_component_100m_anomaly"),
        wind_v_component_100m_mean=data.get("wind_v_component_100m_mean"),
        wind_v_component_100m_anomaly=data.get("wind_v_component_100m_anomaly"),
        snowfall_water_equivalent_mean=data.get("snowfall_water_equivalent_mean"),
        snowfall_water_equivalent_anomaly=data.get("snowfall_water_equivalent_anomaly"),
        precipitation_mean=data.get("precipitation_mean"),
        precipitation_anomaly=data.get("precipitation_anomaly"),
        cloud_cover_mean=data.get("cloud_cover_mean"),
        cloud_cover_anomaly=data.get("cloud_cover_anomaly"),
        sunshine_duration_mean=data.get("sunshine_duration_mean"),
        sunshine_duration_anomaly=data.get("sunshine_duration_anomaly"),
        soil_temperature_0_to_7cm_mean=data.get("soil_temperature_0_to_7cm_mean"),
        soil_temperature_0_to_7cm_anomaly=data.get("soil_temperature_0_to_7cm_anomaly"),
        temperature_max6h_2m_mean=data.get("temperature_max6h_2m_mean"),
        temperature_max6h_2m_anomaly=data.get("temperature_max6h_2m_anomaly"),
        temperature_min6h_2m_mean=data.get("temperature_min6h_2m_mean"),
        temperature_min6h_2m_anomaly=data.get("temperature_min6h_2m_anomaly"),
    )


@dataclass
class GetV1SeasonalResponseMonthly:
    """The ``GetV1SeasonalResponseMonthly`` model."""

    time: list[str] | None = None
    wind_gusts_10m_anomaly: list[float] | None = None
    wind_speed_10m_mean: list[float] | None = None
    wind_speed_10m_anomaly: list[float] | None = None
    albedo_mean: list[float] | None = None
    albedo_anomaly: list[float] | None = None
    cloud_cover_low_mean: list[float] | None = None
    cloud_cover_low_anomaly: list[float] | None = None
    showers_mean: list[float] | None = None
    showers_anomaly: list[float] | None = None
    runoff_mean: list[float] | None = None
    runoff_anomaly: list[float] | None = None
    snow_density_mean: list[float] | None = None
    snow_density_anomaly: list[float] | None = None
    snow_depth_water_equivalent_mean: list[float] | None = None
    snow_depth_water_equivalent_anomaly: list[float] | None = None
    total_column_integrated_water_vapour_mean: list[float] | None = None
    total_column_integrated_water_vapour_anomaly: list[float] | None = None
    temperature_2m_mean: list[float] | None = None
    temperature_2m_anomaly: list[float] | None = None
    dew_point_2m_mean: list[float] | None = None
    dew_point_2m_anomaly: list[float] | None = None
    pressure_msl_mean: list[float] | None = None
    pressure_msl_anomaly: list[float] | None = None
    sea_surface_temperature_mean: list[float] | None = None
    sea_surface_temperature_anomaly: list[float] | None = None
    wind_u_component_10m_mean: list[float] | None = None
    wind_u_component_10m_anomaly: list[float] | None = None
    wind_v_component_10m_mean: list[float] | None = None
    wind_v_component_10m_anomaly: list[float] | None = None
    snowfall_water_equivalent_mean: list[float] | None = None
    snowfall_water_equivalent_anomaly: list[float] | None = None
    precipitation_mean: list[float] | None = None
    precipitation_anomaly: list[float] | None = None
    shortwave_radiation_mean: list[float] | None = None
    shortwave_radiation_anomaly: list[float] | None = None
    longwave_radiation_mean: list[float] | None = None
    longwave_radiation_anomaly: list[float] | None = None
    cloud_cover_mean: list[float] | None = None
    cloud_cover_anomaly: list[float] | None = None
    sunshine_duration_mean: list[float] | None = None
    sunshine_duration_anomaly: list[float] | None = None
    soil_temperature_0_to_7cm_mean: list[float] | None = None
    soil_temperature_0_to_7cm_anomaly: list[float] | None = None
    soil_temperature_7_to_28cm_mean: list[float] | None = None
    soil_temperature_7_to_28cm_anomaly: list[float] | None = None
    soil_temperature_28_to_100cm_mean: list[float] | None = None
    soil_temperature_28_to_100cm_anomaly: list[float] | None = None
    soil_temperature_100_to_255cm_mean: list[float] | None = None
    soil_temperature_100_to_255cm_anomaly: list[float] | None = None
    soil_moisture_0_to_7cm_mean: list[float] | None = None
    soil_moisture_0_to_7cm_anomaly: list[float] | None = None
    soil_moisture_7_to_28cm_mean: list[float] | None = None
    soil_moisture_7_to_28cm_anomaly: list[float] | None = None
    soil_moisture_28_to_100cm_mean: list[float] | None = None
    soil_moisture_28_to_100cm_anomaly: list[float] | None = None
    soil_moisture_100_to_255cm_mean: list[float] | None = None
    soil_moisture_100_to_255cm_anomaly: list[float] | None = None
    temperature_max24h_2m_mean: list[float] | None = None
    temperature_max24h_2m_anomaly: list[float] | None = None
    temperature_min24h_2m_mean: list[float] | None = None
    temperature_min24h_2m_anomaly: list[float] | None = None
    sea_ice_cover_mean: list[float] | None = None
    sea_ice_cover_anomaly: list[float] | None = None
    latent_heat_flux_mean: list[float] | None = None
    latent_heat_flux_anomaly: list[float] | None = None
    sensible_heat_flux_mean: list[float] | None = None
    sensible_heat_flux_anomaly: list[float] | None = None
    evapotranspiration_mean: list[float] | None = None
    evapotranspiration_anomaly: list[float] | None = None
    snowfall_mean: list[float] | None = None
    snowfall_anomaly: list[float] | None = None
    snow_depth_mean: list[float] | None = None
    snow_depth_anomaly: list[float] | None = None


def get_v1_seasonal_response_monthly_from_json(data: Any) -> GetV1SeasonalResponseMonthly:
    """
    Build a :py:class:`GetV1SeasonalResponseMonthly` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the GetV1SeasonalResponseMonthly
    """
    return GetV1SeasonalResponseMonthly(
        time=data.get("time"),
        wind_gusts_10m_anomaly=data.get("wind_gusts_10m_anomaly"),
        wind_speed_10m_mean=data.get("wind_speed_10m_mean"),
        wind_speed_10m_anomaly=data.get("wind_speed_10m_anomaly"),
        albedo_mean=data.get("albedo_mean"),
        albedo_anomaly=data.get("albedo_anomaly"),
        cloud_cover_low_mean=data.get("cloud_cover_low_mean"),
        cloud_cover_low_anomaly=data.get("cloud_cover_low_anomaly"),
        showers_mean=data.get("showers_mean"),
        showers_anomaly=data.get("showers_anomaly"),
        runoff_mean=data.get("runoff_mean"),
        runoff_anomaly=data.get("runoff_anomaly"),
        snow_density_mean=data.get("snow_density_mean"),
        snow_density_anomaly=data.get("snow_density_anomaly"),
        snow_depth_water_equivalent_mean=data.get("snow_depth_water_equivalent_mean"),
        snow_depth_water_equivalent_anomaly=data.get("snow_depth_water_equivalent_anomaly"),
        total_column_integrated_water_vapour_mean=(
            data.get("total_column_integrated_water_vapour_mean")
        ),
        total_column_integrated_water_vapour_anomaly=(
            data.get("total_column_integrated_water_vapour_anomaly")
        ),
        temperature_2m_mean=data.get("temperature_2m_mean"),
        temperature_2m_anomaly=data.get("temperature_2m_anomaly"),
        dew_point_2m_mean=data.get("dew_point_2m_mean"),
        dew_point_2m_anomaly=data.get("dew_point_2m_anomaly"),
        pressure_msl_mean=data.get("pressure_msl_mean"),
        pressure_msl_anomaly=data.get("pressure_msl_anomaly"),
        sea_surface_temperature_mean=data.get("sea_surface_temperature_mean"),
        sea_surface_temperature_anomaly=data.get("sea_surface_temperature_anomaly"),
        wind_u_component_10m_mean=data.get("wind_u_component_10m_mean"),
        wind_u_component_10m_anomaly=data.get("wind_u_component_10m_anomaly"),
        wind_v_component_10m_mean=data.get("wind_v_component_10m_mean"),
        wind_v_component_10m_anomaly=data.get("wind_v_component_10m_anomaly"),
        snowfall_water_equivalent_mean=data.get("snowfall_water_equivalent_mean"),
        snowfall_water_equivalent_anomaly=data.get("snowfall_water_equivalent_anomaly"),
        precipitation_mean=data.get("precipitation_mean"),
        precipitation_anomaly=data.get("precipitation_anomaly"),
        shortwave_radiation_mean=data.get("shortwave_radiation_mean"),
        shortwave_radiation_anomaly=data.get("shortwave_radiation_anomaly"),
        longwave_radiation_mean=data.get("longwave_radiation_mean"),
        longwave_radiation_anomaly=data.get("longwave_radiation_anomaly"),
        cloud_cover_mean=data.get("cloud_cover_mean"),
        cloud_cover_anomaly=data.get("cloud_cover_anomaly"),
        sunshine_duration_mean=data.get("sunshine_duration_mean"),
        sunshine_duration_anomaly=data.get("sunshine_duration_anomaly"),
        soil_temperature_0_to_7cm_mean=data.get("soil_temperature_0_to_7cm_mean"),
        soil_temperature_0_to_7cm_anomaly=data.get("soil_temperature_0_to_7cm_anomaly"),
        soil_temperature_7_to_28cm_mean=data.get("soil_temperature_7_to_28cm_mean"),
        soil_temperature_7_to_28cm_anomaly=data.get("soil_temperature_7_to_28cm_anomaly"),
        soil_temperature_28_to_100cm_mean=data.get("soil_temperature_28_to_100cm_mean"),
        soil_temperature_28_to_100cm_anomaly=data.get("soil_temperature_28_to_100cm_anomaly"),
        soil_temperature_100_to_255cm_mean=data.get("soil_temperature_100_to_255cm_mean"),
        soil_temperature_100_to_255cm_anomaly=data.get("soil_temperature_100_to_255cm_anomaly"),
        soil_moisture_0_to_7cm_mean=data.get("soil_moisture_0_to_7cm_mean"),
        soil_moisture_0_to_7cm_anomaly=data.get("soil_moisture_0_to_7cm_anomaly"),
        soil_moisture_7_to_28cm_mean=data.get("soil_moisture_7_to_28cm_mean"),
        soil_moisture_7_to_28cm_anomaly=data.get("soil_moisture_7_to_28cm_anomaly"),
        soil_moisture_28_to_100cm_mean=data.get("soil_moisture_28_to_100cm_mean"),
        soil_moisture_28_to_100cm_anomaly=data.get("soil_moisture_28_to_100cm_anomaly"),
        soil_moisture_100_to_255cm_mean=data.get("soil_moisture_100_to_255cm_mean"),
        soil_moisture_100_to_255cm_anomaly=data.get("soil_moisture_100_to_255cm_anomaly"),
        temperature_max24h_2m_mean=data.get("temperature_max24h_2m_mean"),
        temperature_max24h_2m_anomaly=data.get("temperature_max24h_2m_anomaly"),
        temperature_min24h_2m_mean=data.get("temperature_min24h_2m_mean"),
        temperature_min24h_2m_anomaly=data.get("temperature_min24h_2m_anomaly"),
        sea_ice_cover_mean=data.get("sea_ice_cover_mean"),
        sea_ice_cover_anomaly=data.get("sea_ice_cover_anomaly"),
        latent_heat_flux_mean=data.get("latent_heat_flux_mean"),
        latent_heat_flux_anomaly=data.get("latent_heat_flux_anomaly"),
        sensible_heat_flux_mean=data.get("sensible_heat_flux_mean"),
        sensible_heat_flux_anomaly=data.get("sensible_heat_flux_anomaly"),
        evapotranspiration_mean=data.get("evapotranspiration_mean"),
        evapotranspiration_anomaly=data.get("evapotranspiration_anomaly"),
        snowfall_mean=data.get("snowfall_mean"),
        snowfall_anomaly=data.get("snowfall_anomaly"),
        snow_depth_mean=data.get("snow_depth_mean"),
        snow_depth_anomaly=data.get("snow_depth_anomaly"),
    )


@dataclass
class GetV1SeasonalResponseMonthlyUnits:
    """The ``GetV1SeasonalResponseMonthlyUnits`` model."""

    time: str | None = None
    wind_gusts_10m_anomaly: str | None = None
    wind_speed_10m_mean: str | None = None
    wind_speed_10m_anomaly: str | None = None
    albedo_mean: str | None = None
    albedo_anomaly: str | None = None
    cloud_cover_low_mean: str | None = None
    cloud_cover_low_anomaly: str | None = None
    showers_mean: str | None = None
    showers_anomaly: str | None = None
    runoff_mean: str | None = None
    runoff_anomaly: str | None = None
    snow_density_mean: str | None = None
    snow_density_anomaly: str | None = None
    snow_depth_water_equivalent_mean: str | None = None
    snow_depth_water_equivalent_anomaly: str | None = None
    total_column_integrated_water_vapour_mean: str | None = None
    total_column_integrated_water_vapour_anomaly: str | None = None
    temperature_2m_mean: str | None = None
    temperature_2m_anomaly: str | None = None
    dew_point_2m_mean: str | None = None
    dew_point_2m_anomaly: str | None = None
    pressure_msl_mean: str | None = None
    pressure_msl_anomaly: str | None = None
    sea_surface_temperature_mean: str | None = None
    sea_surface_temperature_anomaly: str | None = None
    wind_u_component_10m_mean: str | None = None
    wind_u_component_10m_anomaly: str | None = None
    wind_v_component_10m_mean: str | None = None
    wind_v_component_10m_anomaly: str | None = None
    snowfall_water_equivalent_mean: str | None = None
    snowfall_water_equivalent_anomaly: str | None = None
    precipitation_mean: str | None = None
    precipitation_anomaly: str | None = None
    shortwave_radiation_mean: str | None = None
    shortwave_radiation_anomaly: str | None = None
    longwave_radiation_mean: str | None = None
    longwave_radiation_anomaly: str | None = None
    cloud_cover_mean: str | None = None
    cloud_cover_anomaly: str | None = None
    sunshine_duration_mean: str | None = None
    sunshine_duration_anomaly: str | None = None
    soil_temperature_0_to_7cm_mean: str | None = None
    soil_temperature_0_to_7cm_anomaly: str | None = None
    soil_temperature_7_to_28cm_mean: str | None = None
    soil_temperature_7_to_28cm_anomaly: str | None = None
    soil_temperature_28_to_100cm_mean: str | None = None
    soil_temperature_28_to_100cm_anomaly: str | None = None
    soil_temperature_100_to_255cm_mean: str | None = None
    soil_temperature_100_to_255cm_anomaly: str | None = None
    soil_moisture_0_to_7cm_mean: str | None = None
    soil_moisture_0_to_7cm_anomaly: str | None = None
    soil_moisture_7_to_28cm_mean: str | None = None
    soil_moisture_7_to_28cm_anomaly: str | None = None
    soil_moisture_28_to_100cm_mean: str | None = None
    soil_moisture_28_to_100cm_anomaly: str | None = None
    soil_moisture_100_to_255cm_mean: str | None = None
    soil_moisture_100_to_255cm_anomaly: str | None = None
    temperature_max24h_2m_mean: str | None = None
    temperature_max24h_2m_anomaly: str | None = None
    temperature_min24h_2m_mean: str | None = None
    temperature_min24h_2m_anomaly: str | None = None
    sea_ice_cover_mean: str | None = None
    sea_ice_cover_anomaly: str | None = None
    latent_heat_flux_mean: str | None = None
    latent_heat_flux_anomaly: str | None = None
    sensible_heat_flux_mean: str | None = None
    sensible_heat_flux_anomaly: str | None = None
    evapotranspiration_mean: str | None = None
    evapotranspiration_anomaly: str | None = None
    snowfall_mean: str | None = None
    snowfall_anomaly: str | None = None
    snow_depth_mean: str | None = None
    snow_depth_anomaly: str | None = None


def get_v1_seasonal_response_monthly_units_from_json(
    data: Any,
) -> GetV1SeasonalResponseMonthlyUnits:
    """
    Build a :py:class:`GetV1SeasonalResponseMonthlyUnits` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the GetV1SeasonalResponseMonthlyUnits
    """
    return GetV1SeasonalResponseMonthlyUnits(
        time=data.get("time"),
        wind_gusts_10m_anomaly=data.get("wind_gusts_10m_anomaly"),
        wind_speed_10m_mean=data.get("wind_speed_10m_mean"),
        wind_speed_10m_anomaly=data.get("wind_speed_10m_anomaly"),
        albedo_mean=data.get("albedo_mean"),
        albedo_anomaly=data.get("albedo_anomaly"),
        cloud_cover_low_mean=data.get("cloud_cover_low_mean"),
        cloud_cover_low_anomaly=data.get("cloud_cover_low_anomaly"),
        showers_mean=data.get("showers_mean"),
        showers_anomaly=data.get("showers_anomaly"),
        runoff_mean=data.get("runoff_mean"),
        runoff_anomaly=data.get("runoff_anomaly"),
        snow_density_mean=data.get("snow_density_mean"),
        snow_density_anomaly=data.get("snow_density_anomaly"),
        snow_depth_water_equivalent_mean=data.get("snow_depth_water_equivalent_mean"),
        snow_depth_water_equivalent_anomaly=data.get("snow_depth_water_equivalent_anomaly"),
        total_column_integrated_water_vapour_mean=(
            data.get("total_column_integrated_water_vapour_mean")
        ),
        total_column_integrated_water_vapour_anomaly=(
            data.get("total_column_integrated_water_vapour_anomaly")
        ),
        temperature_2m_mean=data.get("temperature_2m_mean"),
        temperature_2m_anomaly=data.get("temperature_2m_anomaly"),
        dew_point_2m_mean=data.get("dew_point_2m_mean"),
        dew_point_2m_anomaly=data.get("dew_point_2m_anomaly"),
        pressure_msl_mean=data.get("pressure_msl_mean"),
        pressure_msl_anomaly=data.get("pressure_msl_anomaly"),
        sea_surface_temperature_mean=data.get("sea_surface_temperature_mean"),
        sea_surface_temperature_anomaly=data.get("sea_surface_temperature_anomaly"),
        wind_u_component_10m_mean=data.get("wind_u_component_10m_mean"),
        wind_u_component_10m_anomaly=data.get("wind_u_component_10m_anomaly"),
        wind_v_component_10m_mean=data.get("wind_v_component_10m_mean"),
        wind_v_component_10m_anomaly=data.get("wind_v_component_10m_anomaly"),
        snowfall_water_equivalent_mean=data.get("snowfall_water_equivalent_mean"),
        snowfall_water_equivalent_anomaly=data.get("snowfall_water_equivalent_anomaly"),
        precipitation_mean=data.get("precipitation_mean"),
        precipitation_anomaly=data.get("precipitation_anomaly"),
        shortwave_radiation_mean=data.get("shortwave_radiation_mean"),
        shortwave_radiation_anomaly=data.get("shortwave_radiation_anomaly"),
        longwave_radiation_mean=data.get("longwave_radiation_mean"),
        longwave_radiation_anomaly=data.get("longwave_radiation_anomaly"),
        cloud_cover_mean=data.get("cloud_cover_mean"),
        cloud_cover_anomaly=data.get("cloud_cover_anomaly"),
        sunshine_duration_mean=data.get("sunshine_duration_mean"),
        sunshine_duration_anomaly=data.get("sunshine_duration_anomaly"),
        soil_temperature_0_to_7cm_mean=data.get("soil_temperature_0_to_7cm_mean"),
        soil_temperature_0_to_7cm_anomaly=data.get("soil_temperature_0_to_7cm_anomaly"),
        soil_temperature_7_to_28cm_mean=data.get("soil_temperature_7_to_28cm_mean"),
        soil_temperature_7_to_28cm_anomaly=data.get("soil_temperature_7_to_28cm_anomaly"),
        soil_temperature_28_to_100cm_mean=data.get("soil_temperature_28_to_100cm_mean"),
        soil_temperature_28_to_100cm_anomaly=data.get("soil_temperature_28_to_100cm_anomaly"),
        soil_temperature_100_to_255cm_mean=data.get("soil_temperature_100_to_255cm_mean"),
        soil_temperature_100_to_255cm_anomaly=data.get("soil_temperature_100_to_255cm_anomaly"),
        soil_moisture_0_to_7cm_mean=data.get("soil_moisture_0_to_7cm_mean"),
        soil_moisture_0_to_7cm_anomaly=data.get("soil_moisture_0_to_7cm_anomaly"),
        soil_moisture_7_to_28cm_mean=data.get("soil_moisture_7_to_28cm_mean"),
        soil_moisture_7_to_28cm_anomaly=data.get("soil_moisture_7_to_28cm_anomaly"),
        soil_moisture_28_to_100cm_mean=data.get("soil_moisture_28_to_100cm_mean"),
        soil_moisture_28_to_100cm_anomaly=data.get("soil_moisture_28_to_100cm_anomaly"),
        soil_moisture_100_to_255cm_mean=data.get("soil_moisture_100_to_255cm_mean"),
        soil_moisture_100_to_255cm_anomaly=data.get("soil_moisture_100_to_255cm_anomaly"),
        temperature_max24h_2m_mean=data.get("temperature_max24h_2m_mean"),
        temperature_max24h_2m_anomaly=data.get("temperature_max24h_2m_anomaly"),
        temperature_min24h_2m_mean=data.get("temperature_min24h_2m_mean"),
        temperature_min24h_2m_anomaly=data.get("temperature_min24h_2m_anomaly"),
        sea_ice_cover_mean=data.get("sea_ice_cover_mean"),
        sea_ice_cover_anomaly=data.get("sea_ice_cover_anomaly"),
        latent_heat_flux_mean=data.get("latent_heat_flux_mean"),
        latent_heat_flux_anomaly=data.get("latent_heat_flux_anomaly"),
        sensible_heat_flux_mean=data.get("sensible_heat_flux_mean"),
        sensible_heat_flux_anomaly=data.get("sensible_heat_flux_anomaly"),
        evapotranspiration_mean=data.get("evapotranspiration_mean"),
        evapotranspiration_anomaly=data.get("evapotranspiration_anomaly"),
        snowfall_mean=data.get("snowfall_mean"),
        snowfall_anomaly=data.get("snowfall_anomaly"),
        snow_depth_mean=data.get("snow_depth_mean"),
        snow_depth_anomaly=data.get("snow_depth_anomaly"),
    )


@dataclass
class GetV1SeasonalResponse:
    """The ``GetV1SeasonalResponse`` model."""

    latitude: float | None = None
    longitude: float | None = None
    elevation: float | None = None
    generationtime_ms: float | None = None
    utc_offset_seconds: int | None = None
    timezone: str | None = None
    timezone_abbreviation: str | None = None
    hourly: GetV1SeasonalResponseHourly | None = None
    hourly_units: GetV1SeasonalResponseHourlyUnits | None = None
    daily: GetV1SeasonalResponseDaily | None = None
    daily_units: GetV1SeasonalResponseDailyUnits | None = None
    weekly: GetV1SeasonalResponseWeekly | None = None
    weekly_units: GetV1SeasonalResponseWeeklyUnits | None = None
    monthly: GetV1SeasonalResponseMonthly | None = None
    monthly_units: GetV1SeasonalResponseMonthlyUnits | None = None


def get_v1_seasonal_response_from_json(data: Any) -> GetV1SeasonalResponse:
    """
    Build a :py:class:`GetV1SeasonalResponse` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the GetV1SeasonalResponse
    """
    return GetV1SeasonalResponse(
        latitude=data.get("latitude"),
        longitude=data.get("longitude"),
        elevation=data.get("elevation"),
        generationtime_ms=data.get("generationtime_ms"),
        utc_offset_seconds=data.get("utc_offset_seconds"),
        timezone=data.get("timezone"),
        timezone_abbreviation=data.get("timezone_abbreviation"),
        hourly=(
            get_v1_seasonal_response_hourly_from_json(data["hourly"])
            if data.get("hourly") is not None
            else None
        ),
        hourly_units=(
            get_v1_seasonal_response_hourly_units_from_json(data["hourly_units"])
            if data.get("hourly_units") is not None
            else None
        ),
        daily=(
            get_v1_seasonal_response_daily_from_json(data["daily"])
            if data.get("daily") is not None
            else None
        ),
        daily_units=(
            get_v1_seasonal_response_daily_units_from_json(data["daily_units"])
            if data.get("daily_units") is not None
            else None
        ),
        weekly=(
            get_v1_seasonal_response_weekly_from_json(data["weekly"])
            if data.get("weekly") is not None
            else None
        ),
        weekly_units=(
            get_v1_seasonal_response_weekly_units_from_json(data["weekly_units"])
            if data.get("weekly_units") is not None
            else None
        ),
        monthly=(
            get_v1_seasonal_response_monthly_from_json(data["monthly"])
            if data.get("monthly") is not None
            else None
        ),
        monthly_units=(
            get_v1_seasonal_response_monthly_units_from_json(data["monthly_units"])
            if data.get("monthly_units") is not None
            else None
        ),
    )
